version: "3.8"

services:
  db:
    image: mysql:8
    container_name: mysql_container
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql
      - ./db/db_sia_dump.sql:/docker-entrypoint-initdb.d/db_sia_dump.sql
    ports:
      - "3308:3306"
    restart: always # Reiniciar siempre el contenedor

  backend:
    build:
      context: ./apiSIA
      dockerfile: Dockerfile.backend
    command: sh -c "ls && ./wait_db.sh db && npm start"
    container_name: backend_container
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      API_PORT: ${API_PORT}
      API_HOST: ${API_HOST}
      FRONTEND_PORT: ${FRONTEND_PORT}
    volumes:
      - ./apiSIA:/app
    depends_on:
      - db
    restart: always # Reiniciar siempre el contenedor

  frontend:
    build:
      context: ./SIA
      dockerfile: Dockerfile.frontend
    container_name: frontend_container
    env_file:
      - .env
    ports:
      - "4000:80"
    depends_on:
      - backend
    restart: always # Reiniciar siempre el contenedor

volumes:
  db_data:
